//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACServices.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMERCIO
    {
        public int ID { get; set; }
        public int FK_TIP_COM { get; set; }
        public int FK_ERP_LOCALIDADES { get; set; }
        public int FK_ERP_PROVINCIAS { get; set; }
        public string NOMBRE { get; set; }
        public string CALLE { get; set; }
        public string NUMERO { get; set; }
        public string LATITUD { get; set; }
        public string LONGITUD { get; set; }
    }
}
