//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACServices.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_EMPRESAS
    {
        public string ID { get; set; }
        public string NOM_FANTASIA { get; set; }
        public string Z_FK_ERP_LOCALIDADES { get; set; }
        public string Z_FK_ERP_PARTIDOS { get; set; }
        public string Z_FK_ERP_PROVINCIAS { get; set; }
        public int FK_ERP_ASESORES { get; set; }
        public int FK_ERP_ASESORES2 { get; set; }
        public int FK_ERP_ASESORES3 { get; set; }
    }
}
