//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACServices.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_ASESORES
    {
        public int ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string C_EMAIL { get; set; }
        public string C_IMEI { get; set; }
        public Nullable<bool> C_IMEI_ADMIN { get; set; }

		public override bool Equals(object obj)
		{
			ERP_ASESORES asesor = (ERP_ASESORES)obj;
			if (ID == asesor.ID && DESCRIPCION == asesor.DESCRIPCION && C_EMAIL == asesor.C_EMAIL &&
				C_IMEI == asesor.C_IMEI && C_IMEI_ADMIN == asesor.C_IMEI_ADMIN)
				return true;
			return false;
		}
	}
}
